/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OfficialResponseAuthorization = IDL.Record({
  'requestorId' : IDL.Opt(IDL.Principal),
  'companyId' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'expired' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Time = IDL.Int;
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'none' : IDL.Null,
  'paid' : IDL.Null,
  'failed' : IDL.Null,
});
export const SubscriptionPlan = IDL.Record({
  'planId' : IDL.Text,
  'priceEur' : IDL.Nat,
});
export const Subscription = IDL.Record({
  'status' : SubscriptionStatus,
  'currentPeriodStart' : IDL.Opt(Time),
  'lastPaymentStatus' : PaymentStatus,
  'plan' : SubscriptionPlan,
  'currentPeriodEnd' : IDL.Opt(Time),
  'lastPaymentAt' : IDL.Opt(Time),
  'autoRenew' : IDL.Bool,
});
export const OfficialProfileRequest = IDL.Record({
  'status' : IDL.Text,
  'requestor' : IDL.Principal,
  'subscription' : Subscription,
  'createdAt' : Time,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'confirmationDocument' : IDL.Text,
  'approvalTimestamp' : IDL.Opt(Time),
  'registrationNumber' : IDL.Text,
  'website' : IDL.Opt(IDL.Text),
  'tradeRegisterLink' : IDL.Text,
  'timestamp' : Time,
  'companyName' : IDL.Text,
});
export const UserProfile = IDL.Record({});
export const Company = IDL.Record({
  'ownerName' : IDL.Text,
  'averageWorkConditionsRating' : IDL.Float64,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'averageJobSecurityRating' : IDL.Float64,
  'sector' : IDL.Text,
  'averageManagementRating' : IDL.Float64,
  'registrationNumber' : IDL.Text,
  'website' : IDL.Opt(IDL.Text),
  'overallRating' : IDL.Float64,
  'averageOtherRating' : IDL.Float64,
  'averagePayRating' : IDL.Float64,
  'isOfficialEmployer' : IDL.Bool,
});
export const ChangedField = IDL.Record({
  'oldValue' : IDL.Text,
  'newValue' : IDL.Text,
  'fieldName' : IDL.Text,
});
export const CompanyEdit = IDL.Record({
  'editor' : IDL.Principal,
  'registrationNumber' : IDL.Text,
  'timestamp' : Time,
  'changes' : IDL.Vec(ChangedField),
  'reason' : IDL.Text,
});
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});
export const OfficialResponseEdit = IDL.Record({
  'editor' : IDL.Principal,
  'timestamp' : Time,
  'reviewId' : IDL.Text,
  'changes' : IDL.Vec(ChangedField),
  'reason' : IDL.Text,
  'companyId' : IDL.Text,
});
export const OfficialResponse = IDL.Record({
  'content' : IDL.Text,
  'responder' : IDL.Principal,
  'hash' : IDL.Text,
  'evidencePaths' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
  'reviewId' : IDL.Text,
  'editedAt' : IDL.Opt(Time),
  'companyId' : IDL.Text,
});
export const TimePeriod = IDL.Variant({
  'days' : IDL.Null,
  'months' : IDL.Null,
  'years' : IDL.Null,
});
export const RatingValues = IDL.Record({
  'managementRating' : IDL.Float64,
  'workConditionsRating' : IDL.Float64,
  'jobSecurityRating' : IDL.Float64,
  'payRating' : IDL.Float64,
  'overallRating' : IDL.Float64,
  'otherRating' : IDL.Float64,
});
export const Review = IDL.Record({
  'managementRating' : IDL.Float64,
  'content' : IDL.Text,
  'reportCount' : IDL.Nat,
  'workConditionsRating' : IDL.Float64,
  'jobSecurityRating' : IDL.Float64,
  'hash' : IDL.Text,
  'supporters' : IDL.Vec(IDL.Principal),
  'evidencePaths' : IDL.Vec(IDL.Text),
  'payRating' : IDL.Float64,
  'timestamp' : Time,
  'otherRating' : IDL.Float64,
  'reported' : IDL.Bool,
  'companyId' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const UserContextState = IDL.Record({
  'role' : UserRole,
  'rejectedRequest' : IDL.Opt(OfficialProfileRequest),
  'officialProfileStatus' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const SuggestionStatus = IDL.Variant({
  'new' : IDL.Null,
  'planned' : IDL.Null,
  'inReview' : IDL.Null,
  'implemented' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Suggestion = IDL.Record({
  'id' : IDL.Text,
  'status' : SuggestionStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : Time,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'activateOfficialProfile' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkOfficialResponseAuthorization' : IDL.Func(
      [IDL.Text],
      [OfficialResponseAuthorization],
      ['query'],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCompany' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'deactivateOfficialProfile' : IDL.Func([IDL.Text], [], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'editCompany' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'getCallerOfficialProfileRequest' : IDL.Func(
      [],
      [IDL.Opt(OfficialProfileRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
  'getCompanyEditHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CompanyEdit)],
      ['query'],
    ),
  'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
  'getOfficialProfileRequests' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(IDL.Tuple(IDL.Text, OfficialProfileRequest))],
      ['query'],
    ),
  'getOfficialProfileSubscriptionStatus' : IDL.Func(
      [IDL.Text],
      [SubscriptionStatus],
      ['query'],
    ),
  'getOfficialResponseEditHistory' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(OfficialResponseEdit)],
      ['query'],
    ),
  'getOfficialResponseForReview' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(OfficialResponse)],
      ['query'],
    ),
  'getOfficialResponsesForCompany' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(OfficialResponse)],
      ['query'],
    ),
  'getOfficialResponsesForReview' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(OfficialResponse)],
      ['query'],
    ),
  'getRatingHistory' : IDL.Func(
      [IDL.Text, TimePeriod],
      [IDL.Vec(IDL.Tuple(Time, RatingValues))],
      ['query'],
    ),
  'getReportCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getReviewsForCompany' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSubscriptionExpirationDate' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Time)],
      ['query'],
    ),
  'getUserContextState' : IDL.Func([], [UserContextState], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasOfficialResponseForReview' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'listSuggestions' : IDL.Func([], [IDL.Vec(Suggestion)], ['query']),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'reportReview' : IDL.Func([IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitOfficialProfileRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitOfficialResponse' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'submitReview' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'submitSuggestion' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'supportReview' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCompanyRatings' : IDL.Func([IDL.Text, RatingValues], [], []),
  'updateOfficialProfileRequestStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateSuggestionStatus' : IDL.Func([IDL.Text, SuggestionStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OfficialResponseAuthorization = IDL.Record({
    'requestorId' : IDL.Opt(IDL.Principal),
    'companyId' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'expired' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Time = IDL.Int;
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'none' : IDL.Null,
    'paid' : IDL.Null,
    'failed' : IDL.Null,
  });
  const SubscriptionPlan = IDL.Record({
    'planId' : IDL.Text,
    'priceEur' : IDL.Nat,
  });
  const Subscription = IDL.Record({
    'status' : SubscriptionStatus,
    'currentPeriodStart' : IDL.Opt(Time),
    'lastPaymentStatus' : PaymentStatus,
    'plan' : SubscriptionPlan,
    'currentPeriodEnd' : IDL.Opt(Time),
    'lastPaymentAt' : IDL.Opt(Time),
    'autoRenew' : IDL.Bool,
  });
  const OfficialProfileRequest = IDL.Record({
    'status' : IDL.Text,
    'requestor' : IDL.Principal,
    'subscription' : Subscription,
    'createdAt' : Time,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'confirmationDocument' : IDL.Text,
    'approvalTimestamp' : IDL.Opt(Time),
    'registrationNumber' : IDL.Text,
    'website' : IDL.Opt(IDL.Text),
    'tradeRegisterLink' : IDL.Text,
    'timestamp' : Time,
    'companyName' : IDL.Text,
  });
  const UserProfile = IDL.Record({});
  const Company = IDL.Record({
    'ownerName' : IDL.Text,
    'averageWorkConditionsRating' : IDL.Float64,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'averageJobSecurityRating' : IDL.Float64,
    'sector' : IDL.Text,
    'averageManagementRating' : IDL.Float64,
    'registrationNumber' : IDL.Text,
    'website' : IDL.Opt(IDL.Text),
    'overallRating' : IDL.Float64,
    'averageOtherRating' : IDL.Float64,
    'averagePayRating' : IDL.Float64,
    'isOfficialEmployer' : IDL.Bool,
  });
  const ChangedField = IDL.Record({
    'oldValue' : IDL.Text,
    'newValue' : IDL.Text,
    'fieldName' : IDL.Text,
  });
  const CompanyEdit = IDL.Record({
    'editor' : IDL.Principal,
    'registrationNumber' : IDL.Text,
    'timestamp' : Time,
    'changes' : IDL.Vec(ChangedField),
    'reason' : IDL.Text,
  });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const OfficialResponseEdit = IDL.Record({
    'editor' : IDL.Principal,
    'timestamp' : Time,
    'reviewId' : IDL.Text,
    'changes' : IDL.Vec(ChangedField),
    'reason' : IDL.Text,
    'companyId' : IDL.Text,
  });
  const OfficialResponse = IDL.Record({
    'content' : IDL.Text,
    'responder' : IDL.Principal,
    'hash' : IDL.Text,
    'evidencePaths' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
    'reviewId' : IDL.Text,
    'editedAt' : IDL.Opt(Time),
    'companyId' : IDL.Text,
  });
  const TimePeriod = IDL.Variant({
    'days' : IDL.Null,
    'months' : IDL.Null,
    'years' : IDL.Null,
  });
  const RatingValues = IDL.Record({
    'managementRating' : IDL.Float64,
    'workConditionsRating' : IDL.Float64,
    'jobSecurityRating' : IDL.Float64,
    'payRating' : IDL.Float64,
    'overallRating' : IDL.Float64,
    'otherRating' : IDL.Float64,
  });
  const Review = IDL.Record({
    'managementRating' : IDL.Float64,
    'content' : IDL.Text,
    'reportCount' : IDL.Nat,
    'workConditionsRating' : IDL.Float64,
    'jobSecurityRating' : IDL.Float64,
    'hash' : IDL.Text,
    'supporters' : IDL.Vec(IDL.Principal),
    'evidencePaths' : IDL.Vec(IDL.Text),
    'payRating' : IDL.Float64,
    'timestamp' : Time,
    'otherRating' : IDL.Float64,
    'reported' : IDL.Bool,
    'companyId' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const UserContextState = IDL.Record({
    'role' : UserRole,
    'rejectedRequest' : IDL.Opt(OfficialProfileRequest),
    'officialProfileStatus' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const SuggestionStatus = IDL.Variant({
    'new' : IDL.Null,
    'planned' : IDL.Null,
    'inReview' : IDL.Null,
    'implemented' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Suggestion = IDL.Record({
    'id' : IDL.Text,
    'status' : SuggestionStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : Time,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'activateOfficialProfile' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkOfficialResponseAuthorization' : IDL.Func(
        [IDL.Text],
        [OfficialResponseAuthorization],
        ['query'],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCompany' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'deactivateOfficialProfile' : IDL.Func([IDL.Text], [], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'editCompany' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'getCallerOfficialProfileRequest' : IDL.Func(
        [],
        [IDL.Opt(OfficialProfileRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
    'getCompanyEditHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CompanyEdit)],
        ['query'],
      ),
    'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
    'getOfficialProfileRequests' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(IDL.Tuple(IDL.Text, OfficialProfileRequest))],
        ['query'],
      ),
    'getOfficialProfileSubscriptionStatus' : IDL.Func(
        [IDL.Text],
        [SubscriptionStatus],
        ['query'],
      ),
    'getOfficialResponseEditHistory' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(OfficialResponseEdit)],
        ['query'],
      ),
    'getOfficialResponseForReview' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(OfficialResponse)],
        ['query'],
      ),
    'getOfficialResponsesForCompany' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(OfficialResponse)],
        ['query'],
      ),
    'getOfficialResponsesForReview' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(OfficialResponse)],
        ['query'],
      ),
    'getRatingHistory' : IDL.Func(
        [IDL.Text, TimePeriod],
        [IDL.Vec(IDL.Tuple(Time, RatingValues))],
        ['query'],
      ),
    'getReportCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getReviewsForCompany' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSubscriptionExpirationDate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Time)],
        ['query'],
      ),
    'getUserContextState' : IDL.Func([], [UserContextState], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasOfficialResponseForReview' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'listSuggestions' : IDL.Func([], [IDL.Vec(Suggestion)], ['query']),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'reportReview' : IDL.Func([IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitOfficialProfileRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitOfficialResponse' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'submitReview' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'submitSuggestion' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'supportReview' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCompanyRatings' : IDL.Func([IDL.Text, RatingValues], [], []),
    'updateOfficialProfileRequestStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateSuggestionStatus' : IDL.Func([IDL.Text, SuggestionStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };