/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ChangedField {
  'oldValue' : string,
  'newValue' : string,
  'fieldName' : string,
}
export interface Company {
  'ownerName' : string,
  'averageWorkConditionsRating' : number,
  'city' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'averageJobSecurityRating' : number,
  'sector' : string,
  'averageManagementRating' : number,
  'registrationNumber' : string,
  'website' : [] | [string],
  'overallRating' : number,
  'averageOtherRating' : number,
  'averagePayRating' : number,
  'isOfficialEmployer' : boolean,
}
export interface CompanyEdit {
  'editor' : Principal,
  'registrationNumber' : string,
  'timestamp' : Time,
  'changes' : Array<ChangedField>,
  'reason' : string,
}
export interface FileReference { 'hash' : string, 'path' : string }
export interface OfficialProfileRequest {
  'status' : string,
  'requestor' : Principal,
  'subscription' : Subscription,
  'createdAt' : Time,
  'rejectionReason' : [] | [string],
  'confirmationDocument' : string,
  'approvalTimestamp' : [] | [Time],
  'registrationNumber' : string,
  'website' : [] | [string],
  'tradeRegisterLink' : string,
  'timestamp' : Time,
  'companyName' : string,
}
export interface OfficialResponse {
  'content' : string,
  'responder' : Principal,
  'hash' : string,
  'evidencePaths' : Array<string>,
  'timestamp' : Time,
  'reviewId' : string,
  'editedAt' : [] | [Time],
  'companyId' : string,
}
export interface OfficialResponseAuthorization {
  'requestorId' : [] | [Principal],
  'companyId' : string,
}
export interface OfficialResponseEdit {
  'editor' : Principal,
  'timestamp' : Time,
  'reviewId' : string,
  'changes' : Array<ChangedField>,
  'reason' : string,
  'companyId' : string,
}
export type PaymentStatus = { 'pending' : null } |
  { 'none' : null } |
  { 'paid' : null } |
  { 'failed' : null };
export interface RatingValues {
  'managementRating' : number,
  'workConditionsRating' : number,
  'jobSecurityRating' : number,
  'payRating' : number,
  'overallRating' : number,
  'otherRating' : number,
}
export interface Review {
  'managementRating' : number,
  'content' : string,
  'reportCount' : bigint,
  'workConditionsRating' : number,
  'jobSecurityRating' : number,
  'hash' : string,
  'supporters' : Array<Principal>,
  'evidencePaths' : Array<string>,
  'payRating' : number,
  'timestamp' : Time,
  'otherRating' : number,
  'reported' : boolean,
  'companyId' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Subscription {
  'status' : SubscriptionStatus,
  'currentPeriodStart' : [] | [Time],
  'lastPaymentStatus' : PaymentStatus,
  'plan' : SubscriptionPlan,
  'currentPeriodEnd' : [] | [Time],
  'lastPaymentAt' : [] | [Time],
  'autoRenew' : boolean,
}
export interface SubscriptionPlan { 'planId' : string, 'priceEur' : bigint }
export type SubscriptionStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'expired' : null } |
  { 'inactive' : null };
export interface Suggestion {
  'id' : string,
  'status' : SuggestionStatus,
  'title' : string,
  'content' : string,
  'sender' : string,
  'timestamp' : Time,
}
export type SuggestionStatus = { 'new' : null } |
  { 'planned' : null } |
  { 'inReview' : null } |
  { 'implemented' : null } |
  { 'rejected' : null };
export type Time = bigint;
export type TimePeriod = { 'days' : null } |
  { 'months' : null } |
  { 'years' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserContextState {
  'role' : UserRole,
  'rejectedRequest' : [] | [OfficialProfileRequest],
  'officialProfileStatus' : string,
}
export type UserProfile = {};
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<string>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<string>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'activateOfficialProfile' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkOfficialResponseAuthorization' : ActorMethod<
    [string],
    OfficialResponseAuthorization
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCompany' : ActorMethod<
    [string, string, string, string, string, string, [] | [string]],
    undefined
  >,
  'deactivateOfficialProfile' : ActorMethod<[string], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'editCompany' : ActorMethod<
    [string, string, string, string, string, string, [] | [string], string],
    undefined
  >,
  'getCallerOfficialProfileRequest' : ActorMethod<
    [],
    [] | [OfficialProfileRequest]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanies' : ActorMethod<[], Array<Company>>,
  'getCompanyEditHistory' : ActorMethod<[string], Array<CompanyEdit>>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getOfficialProfileRequests' : ActorMethod<
    [[] | [string]],
    Array<[string, OfficialProfileRequest]>
  >,
  'getOfficialProfileSubscriptionStatus' : ActorMethod<
    [string],
    SubscriptionStatus
  >,
  'getOfficialResponseEditHistory' : ActorMethod<
    [string, string],
    Array<OfficialResponseEdit>
  >,
  'getOfficialResponseForReview' : ActorMethod<
    [string, string],
    [] | [OfficialResponse]
  >,
  'getOfficialResponsesForCompany' : ActorMethod<
    [string],
    Array<OfficialResponse>
  >,
  'getOfficialResponsesForReview' : ActorMethod<
    [string],
    Array<OfficialResponse>
  >,
  'getRatingHistory' : ActorMethod<
    [string, TimePeriod],
    Array<[Time, RatingValues]>
  >,
  'getReportCount' : ActorMethod<[string], bigint>,
  'getReviewsForCompany' : ActorMethod<[string], Array<Review>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubscriptionExpirationDate' : ActorMethod<[string], [] | [Time]>,
  'getUserContextState' : ActorMethod<[], UserContextState>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasOfficialResponseForReview' : ActorMethod<[string, string], boolean>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'listSuggestions' : ActorMethod<[], Array<Suggestion>>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'reportReview' : ActorMethod<[string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitOfficialProfileRequest' : ActorMethod<
    [string, string, [] | [string], string, string],
    undefined
  >,
  'submitOfficialResponse' : ActorMethod<
    [string, string, string, Array<string>, string, boolean],
    undefined
  >,
  'submitReview' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      string,
      number,
      number,
      number,
      number,
      number,
    ],
    undefined
  >,
  'submitSuggestion' : ActorMethod<[string, string], undefined>,
  'supportReview' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCompanyRatings' : ActorMethod<[string, RatingValues], undefined>,
  'updateOfficialProfileRequestStatus' : ActorMethod<
    [string, string, [] | [string]],
    undefined
  >,
  'updateSuggestionStatus' : ActorMethod<[string, SuggestionStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];