/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserContextState {
    role: UserRole;
    rejectedRequest?: OfficialProfileRequest;
    officialProfileStatus: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Suggestion {
    id: string;
    status: SuggestionStatus;
    title: string;
    content: string;
    sender: string;
    timestamp: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Subscription {
    status: SubscriptionStatus;
    currentPeriodStart?: Time;
    lastPaymentStatus: PaymentStatus;
    plan: SubscriptionPlan;
    currentPeriodEnd?: Time;
    lastPaymentAt?: Time;
    autoRenew: boolean;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface CompanyEdit {
    editor: Principal;
    registrationNumber: string;
    timestamp: Time;
    changes: Array<ChangedField>;
    reason: string;
}
export interface SubscriptionPlan {
    planId: string;
    priceEur: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface FileReference {
    hash: string;
    path: string;
}
export interface Review {
    managementRating: number;
    content: string;
    reportCount: bigint;
    workConditionsRating: number;
    jobSecurityRating: number;
    hash: string;
    supporters: Array<Principal>;
    evidencePaths: Array<string>;
    payRating: number;
    timestamp: Time;
    otherRating: number;
    reported: boolean;
    companyId: string;
}
export interface OfficialResponse {
    content: string;
    responder: Principal;
    hash: string;
    evidencePaths: Array<string>;
    timestamp: Time;
    reviewId: string;
    editedAt?: Time;
    companyId: string;
}
export interface RatingValues {
    managementRating: number;
    workConditionsRating: number;
    jobSecurityRating: number;
    payRating: number;
    overallRating: number;
    otherRating: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Company {
    ownerName: string;
    averageWorkConditionsRating: number;
    city: string;
    name: string;
    createdAt: Time;
    description: string;
    averageJobSecurityRating: number;
    sector: string;
    averageManagementRating: number;
    registrationNumber: string;
    website?: string;
    overallRating: number;
    averageOtherRating: number;
    averagePayRating: number;
    isOfficialEmployer: boolean;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface OfficialResponseAuthorization {
    requestorId?: Principal;
    companyId: string;
}
export interface OfficialResponseEdit {
    editor: Principal;
    timestamp: Time;
    reviewId: string;
    changes: Array<ChangedField>;
    reason: string;
    companyId: string;
}
export interface ChangedField {
    oldValue: string;
    newValue: string;
    fieldName: string;
}
export interface UserProfile {
}
export interface OfficialProfileRequest {
    status: string;
    requestor: Principal;
    subscription: Subscription;
    createdAt: Time;
    rejectionReason?: string;
    confirmationDocument: string;
    approvalTimestamp?: Time;
    registrationNumber: string;
    website?: string;
    tradeRegisterLink: string;
    timestamp: Time;
    companyName: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum PaymentStatus {
    pending = "pending",
    none = "none",
    paid = "paid",
    failed = "failed"
}
export enum SubscriptionStatus {
    active = "active",
    cancelled = "cancelled",
    expired = "expired",
    inactive = "inactive"
}
export enum SuggestionStatus {
    new_ = "new",
    planned = "planned",
    inReview = "inReview",
    implemented = "implemented",
    rejected = "rejected"
}
export enum TimePeriod {
    days = "days",
    months = "months",
    years = "years"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobsToDelete(): Promise<Array<string>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<string>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    activateOfficialProfile(registrationNumber: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkOfficialResponseAuthorization(companyId: string): Promise<OfficialResponseAuthorization>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createCompany(name: string, description: string, ownerName: string, registrationNumber: string, city: string, sector: string, website: string | null): Promise<void>;
    deactivateOfficialProfile(registrationNumber: string): Promise<void>;
    dropFileReference(path: string): Promise<void>;
    editCompany(registrationNumber: string, newName: string, newDescription: string, newOwnerName: string, newCity: string, newSector: string, newWebsite: string | null, reason: string): Promise<void>;
    getCallerOfficialProfileRequest(): Promise<OfficialProfileRequest | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompanies(): Promise<Array<Company>>;
    getCompanyEditHistory(companyId: string): Promise<Array<CompanyEdit>>;
    getFileReference(path: string): Promise<FileReference>;
    getOfficialProfileRequests(filter: string | null): Promise<Array<[string, OfficialProfileRequest]>>;
    getOfficialProfileSubscriptionStatus(registrationNumber: string): Promise<SubscriptionStatus>;
    getOfficialResponseEditHistory(companyId: string, reviewId: string): Promise<Array<OfficialResponseEdit>>;
    getOfficialResponseForReview(companyId: string, reviewId: string): Promise<OfficialResponse | null>;
    getOfficialResponsesForCompany(companyId: string): Promise<Array<OfficialResponse>>;
    getOfficialResponsesForReview(reviewId: string): Promise<Array<OfficialResponse>>;
    getRatingHistory(companyId: string, period: TimePeriod): Promise<Array<[Time, RatingValues]>>;
    getReportCount(hash: string): Promise<bigint>;
    getReviewsForCompany(companyId: string): Promise<Array<Review>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getSubscriptionExpirationDate(registrationNumber: string): Promise<Time | null>;
    getUserContextState(): Promise<UserContextState>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasOfficialResponseForReview(companyId: string, reviewId: string): Promise<boolean>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listFileReferences(): Promise<Array<FileReference>>;
    listSuggestions(): Promise<Array<Suggestion>>;
    registerFileReference(path: string, hash: string): Promise<void>;
    reportReview(hash: string): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitOfficialProfileRequest(companyName: string, registrationNumber: string, website: string | null, tradeRegisterLink: string, confirmationDocument: string): Promise<void>;
    submitOfficialResponse(reviewId: string, companyId: string, content: string, evidencePaths: Array<string>, hash: string, isEdit: boolean): Promise<void>;
    submitReview(companyId: string, content: string, evidencePaths: Array<string>, hash: string, payRating: number, workConditionsRating: number, managementRating: number, jobSecurityRating: number, otherRating: number): Promise<void>;
    submitSuggestion(title: string, content: string): Promise<void>;
    supportReview(hash: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCompanyRatings(companyId: string, newRatings: RatingValues): Promise<void>;
    updateOfficialProfileRequestStatus(requestKey: string, newStatus: string, rejectionReason: string | null): Promise<void>;
    updateSuggestionStatus(id: string, newStatus: SuggestionStatus): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, Company as _Company, OfficialProfileRequest as _OfficialProfileRequest, OfficialResponse as _OfficialResponse, OfficialResponseAuthorization as _OfficialResponseAuthorization, PaymentStatus as _PaymentStatus, StripeSessionStatus as _StripeSessionStatus, Subscription as _Subscription, SubscriptionPlan as _SubscriptionPlan, SubscriptionStatus as _SubscriptionStatus, Suggestion as _Suggestion, SuggestionStatus as _SuggestionStatus, Time as _Time, TimePeriod as _TimePeriod, UserApprovalInfo as _UserApprovalInfo, UserContextState as _UserContextState, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobsToDelete(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async activateOfficialProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateOfficialProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateOfficialProfile(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkOfficialResponseAuthorization(arg0: string): Promise<OfficialResponseAuthorization> {
        if (this.processError) {
            try {
                const result = await this.actor.checkOfficialResponseAuthorization(arg0);
                return from_candid_OfficialResponseAuthorization_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkOfficialResponseAuthorization(arg0);
            return from_candid_OfficialResponseAuthorization_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createCompany(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCompany(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCompany(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async deactivateOfficialProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateOfficialProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateOfficialProfile(arg0);
            return result;
        }
    }
    async dropFileReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dropFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dropFileReference(arg0);
            return result;
        }
    }
    async editCompany(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string | null, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editCompany(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editCompany(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async getCallerOfficialProfileRequest(): Promise<OfficialProfileRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerOfficialProfileRequest();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerOfficialProfileRequest();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanies(): Promise<Array<Company>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanies();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanies();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanyEditHistory(arg0: string): Promise<Array<CompanyEdit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyEditHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyEditHistory(arg0);
            return result;
        }
    }
    async getFileReference(arg0: string): Promise<FileReference> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileReference(arg0);
            return result;
        }
    }
    async getOfficialProfileRequests(arg0: string | null): Promise<Array<[string, OfficialProfileRequest]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficialProfileRequests(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficialProfileRequests(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOfficialProfileSubscriptionStatus(arg0: string): Promise<SubscriptionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficialProfileSubscriptionStatus(arg0);
                return from_candid_SubscriptionStatus_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficialProfileSubscriptionStatus(arg0);
            return from_candid_SubscriptionStatus_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOfficialResponseEditHistory(arg0: string, arg1: string): Promise<Array<OfficialResponseEdit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficialResponseEditHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficialResponseEditHistory(arg0, arg1);
            return result;
        }
    }
    async getOfficialResponseForReview(arg0: string, arg1: string): Promise<OfficialResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficialResponseForReview(arg0, arg1);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficialResponseForReview(arg0, arg1);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOfficialResponsesForCompany(arg0: string): Promise<Array<OfficialResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficialResponsesForCompany(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficialResponsesForCompany(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOfficialResponsesForReview(arg0: string): Promise<Array<OfficialResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficialResponsesForReview(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficialResponsesForReview(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRatingHistory(arg0: string, arg1: TimePeriod): Promise<Array<[Time, RatingValues]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingHistory(arg0, to_candid_TimePeriod_n37(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingHistory(arg0, to_candid_TimePeriod_n37(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getReportCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportCount(arg0);
            return result;
        }
    }
    async getReviewsForCompany(arg0: string): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsForCompany(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsForCompany(arg0);
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionExpirationDate(arg0: string): Promise<Time | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionExpirationDate(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionExpirationDate(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserContextState(): Promise<UserContextState> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserContextState();
                return from_candid_UserContextState_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserContextState();
            return from_candid_UserContextState_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasOfficialResponseForReview(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasOfficialResponseForReview(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasOfficialResponseForReview(arg0, arg1);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFileReferences(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileReferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileReferences();
            return result;
        }
    }
    async listSuggestions(): Promise<Array<Suggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSuggestions();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSuggestions();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerFileReference(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFileReference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFileReference(arg0, arg1);
            return result;
        }
    }
    async reportReview(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportReview(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n54(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n54(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitOfficialProfileRequest(arg0: string, arg1: string, arg2: string | null, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOfficialProfileRequest(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOfficialProfileRequest(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async submitOfficialResponse(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: string, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOfficialResponse(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOfficialResponse(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async submitReview(arg0: string, arg1: string, arg2: Array<string>, arg3: string, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async submitSuggestion(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSuggestion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSuggestion(arg0, arg1);
            return result;
        }
    }
    async supportReview(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.supportReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.supportReview(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCompanyRatings(arg0: string, arg1: RatingValues): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompanyRatings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompanyRatings(arg0, arg1);
            return result;
        }
    }
    async updateOfficialProfileRequestStatus(arg0: string, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOfficialProfileRequestStatus(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOfficialProfileRequestStatus(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateSuggestionStatus(arg0: string, arg1: SuggestionStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSuggestionStatus(arg0, to_candid_SuggestionStatus_n56(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSuggestionStatus(arg0, to_candid_SuggestionStatus_n56(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Company_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Company): Company {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_OfficialProfileRequest_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OfficialProfileRequest): OfficialProfileRequest {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_OfficialResponseAuthorization_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OfficialResponseAuthorization): OfficialResponseAuthorization {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_OfficialResponse_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OfficialResponse): OfficialResponse {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_SuggestionStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SuggestionStatus): SuggestionStatus {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Suggestion_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Suggestion): Suggestion {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserContextState_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserContextState): UserContextState {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OfficialProfileRequest]): OfficialProfileRequest | null {
    return value.length === 0 ? null : from_candid_OfficialProfileRequest_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OfficialResponse]): OfficialResponse | null {
    return value.length === 0 ? null : from_candid_OfficialResponse_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    requestorId: [] | [Principal];
    companyId: string;
}): {
    requestorId?: Principal;
    companyId: string;
} {
    return {
        requestorId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.requestorId)),
        companyId: value.companyId
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    requestor: Principal;
    subscription: _Subscription;
    createdAt: _Time;
    rejectionReason: [] | [string];
    confirmationDocument: string;
    approvalTimestamp: [] | [_Time];
    registrationNumber: string;
    website: [] | [string];
    tradeRegisterLink: string;
    timestamp: _Time;
    companyName: string;
}): {
    status: string;
    requestor: Principal;
    subscription: Subscription;
    createdAt: Time;
    rejectionReason?: string;
    confirmationDocument: string;
    approvalTimestamp?: Time;
    registrationNumber: string;
    website?: string;
    tradeRegisterLink: string;
    timestamp: Time;
    companyName: string;
} {
    return {
        status: value.status,
        requestor: value.requestor,
        subscription: from_candid_Subscription_n17(_uploadFile, _downloadFile, value.subscription),
        createdAt: value.createdAt,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.rejectionReason)),
        confirmationDocument: value.confirmationDocument,
        approvalTimestamp: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.approvalTimestamp)),
        registrationNumber: value.registrationNumber,
        website: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.website)),
        tradeRegisterLink: value.tradeRegisterLink,
        timestamp: value.timestamp,
        companyName: value.companyName
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SubscriptionStatus;
    currentPeriodStart: [] | [_Time];
    lastPaymentStatus: _PaymentStatus;
    plan: _SubscriptionPlan;
    currentPeriodEnd: [] | [_Time];
    lastPaymentAt: [] | [_Time];
    autoRenew: boolean;
}): {
    status: SubscriptionStatus;
    currentPeriodStart?: Time;
    lastPaymentStatus: PaymentStatus;
    plan: SubscriptionPlan;
    currentPeriodEnd?: Time;
    lastPaymentAt?: Time;
    autoRenew: boolean;
} {
    return {
        status: from_candid_SubscriptionStatus_n19(_uploadFile, _downloadFile, value.status),
        currentPeriodStart: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.currentPeriodStart)),
        lastPaymentStatus: from_candid_PaymentStatus_n22(_uploadFile, _downloadFile, value.lastPaymentStatus),
        plan: value.plan,
        currentPeriodEnd: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.currentPeriodEnd)),
        lastPaymentAt: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.lastPaymentAt)),
        autoRenew: value.autoRenew
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ownerName: string;
    averageWorkConditionsRating: number;
    city: string;
    name: string;
    createdAt: _Time;
    description: string;
    averageJobSecurityRating: number;
    sector: string;
    averageManagementRating: number;
    registrationNumber: string;
    website: [] | [string];
    overallRating: number;
    averageOtherRating: number;
    averagePayRating: number;
    isOfficialEmployer: boolean;
}): {
    ownerName: string;
    averageWorkConditionsRating: number;
    city: string;
    name: string;
    createdAt: Time;
    description: string;
    averageJobSecurityRating: number;
    sector: string;
    averageManagementRating: number;
    registrationNumber: string;
    website?: string;
    overallRating: number;
    averageOtherRating: number;
    averagePayRating: number;
    isOfficialEmployer: boolean;
} {
    return {
        ownerName: value.ownerName,
        averageWorkConditionsRating: value.averageWorkConditionsRating,
        city: value.city,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        averageJobSecurityRating: value.averageJobSecurityRating,
        sector: value.sector,
        averageManagementRating: value.averageManagementRating,
        registrationNumber: value.registrationNumber,
        website: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.website)),
        overallRating: value.overallRating,
        averageOtherRating: value.averageOtherRating,
        averagePayRating: value.averagePayRating,
        isOfficialEmployer: value.isOfficialEmployer
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    responder: Principal;
    hash: string;
    evidencePaths: Array<string>;
    timestamp: _Time;
    reviewId: string;
    editedAt: [] | [_Time];
    companyId: string;
}): {
    content: string;
    responder: Principal;
    hash: string;
    evidencePaths: Array<string>;
    timestamp: Time;
    reviewId: string;
    editedAt?: Time;
    companyId: string;
} {
    return {
        content: value.content,
        responder: value.responder,
        hash: value.hash,
        evidencePaths: value.evidencePaths,
        timestamp: value.timestamp,
        reviewId: value.reviewId,
        editedAt: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.editedAt)),
        companyId: value.companyId
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: _UserRole;
    rejectedRequest: [] | [_OfficialProfileRequest];
    officialProfileStatus: string;
}): {
    role: UserRole;
    rejectedRequest?: OfficialProfileRequest;
    officialProfileStatus: string;
} {
    return {
        role: from_candid_UserRole_n26(_uploadFile, _downloadFile, value.role),
        rejectedRequest: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.rejectedRequest)),
        officialProfileStatus: value.officialProfileStatus
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n47(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _SuggestionStatus;
    title: string;
    content: string;
    sender: string;
    timestamp: _Time;
}): {
    id: string;
    status: SuggestionStatus;
    title: string;
    content: string;
    sender: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        status: from_candid_SuggestionStatus_n52(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        sender: value.sender,
        timestamp: value.timestamp
    };
}
function from_candid_tuple_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _OfficialProfileRequest]): [string, OfficialProfileRequest] {
    return [
        value[0],
        from_candid_OfficialProfileRequest_n15(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    expired: null;
} | {
    inactive: null;
}): SubscriptionStatus {
    return "active" in value ? SubscriptionStatus.active : "cancelled" in value ? SubscriptionStatus.cancelled : "expired" in value ? SubscriptionStatus.expired : "inactive" in value ? SubscriptionStatus.inactive : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    none: null;
} | {
    paid: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "none" in value ? PaymentStatus.none : "paid" in value ? PaymentStatus.paid : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n41(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    planned: null;
} | {
    inReview: null;
} | {
    implemented: null;
} | {
    rejected: null;
}): SuggestionStatus {
    return "new" in value ? SuggestionStatus.new : "planned" in value ? SuggestionStatus.planned : "inReview" in value ? SuggestionStatus.inReview : "implemented" in value ? SuggestionStatus.implemented : "rejected" in value ? SuggestionStatus.rejected : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Company>): Array<Company> {
    return value.map((x)=>from_candid_Company_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _OfficialProfileRequest]>): Array<[string, OfficialProfileRequest]> {
    return value.map((x)=>from_candid_tuple_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OfficialResponse>): Array<OfficialResponse> {
    return value.map((x)=>from_candid_OfficialResponse_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Suggestion>): Array<Suggestion> {
    return value.map((x)=>from_candid_Suggestion_n50(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_SuggestionStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SuggestionStatus): _SuggestionStatus {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_TimePeriod_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimePeriod): _TimePeriod {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimePeriod): {
    days: null;
} | {
    months: null;
} | {
    years: null;
} {
    return value == TimePeriod.days ? {
        days: null
    } : value == TimePeriod.months ? {
        months: null
    } : value == TimePeriod.years ? {
        years: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SuggestionStatus): {
    new: null;
} | {
    planned: null;
} | {
    inReview: null;
} | {
    implemented: null;
} | {
    rejected: null;
} {
    return value == SuggestionStatus.new ? {
        new_: null
    } : value == SuggestionStatus.planned ? {
        planned: null
    } : value == SuggestionStatus.inReview ? {
        inReview: null
    } : value == SuggestionStatus.implemented ? {
        implemented: null
    } : value == SuggestionStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
